services:
  db:
      build: ./docker/db/
      platform: linux/x86_64
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: crash_archive
      volumes:
          - ./volumes/mysql:/var/lib/mysql
  ca:
      build: ./docker/ca/
      ports:
          - "8080:80"
      volumes:
          - ./bin:/app
          - ./templates:/app/templates
          - ./config:/app/config
          - ./volumes/reports:/app/reports
          - ./static:/app/static
          - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      links:
          - db:db
